project:
  type: website
  resources:
    - CNAME

website:
  title: "NHS-OA Community website"
  description: "A community for promoting open code and tools in health and care"
  site-url: https://nhsoa.uk
  page-navigation: true
  back-to-top-navigation: true
  favicon: /img/oa-logo_basic.png
  repo-url: https://github.com/nhs-oa-community/nhs-oa-community.github.io
  repo-actions: [edit, issue]
  navbar:
    toggle-position: right
    logo: "img/oa-logo_basic_min_bg.png"
    logo-alt: "NHS-OA Community Logo which consists of the words and incorporating the OA logo"
    title: false
    collapse-below: lg
    tools:
    - icon: github
      href: https://github.com/nhs-oa-community
    right:
      - text: "About"
        href: about.qmd
        aria-label: About page
      - text: "Events"
        href: events/events.qmd
        menu:
        - text: "Workshops and webinars"
          href: webinars-and-workshops.qmd
        - text: "Coffee and Coding"
          href: coffee-and-code.qmd 
      - text: "Blogs"
        href: blog/index.qmd
      - text: "Training"
        href: training/index.qmd 
      - text: "Resources"
        menu:
        - text: "Books"
          href: books/index.qmd
        - text: "Videos"
          href: videos/index.qmd
        - text: "Packages"
          href: packages/r-packages.qmd 
      - text: "Fellowships"
        href: fellowships/fellowship.qmd
        aria-label: Fellowships page
      - text: "Contact Us"
        href: contact.qmd
        aria-label: Contact details

  page-footer:
    left: >-
     NHS-OA Community &#8729; Made with [![Quarto](https://quarto.org/quarto.png){fig-alt="Quarto logo blue round circle with a cross within the circumference" width=65px}](https://quarto.org/)
    center: |
      <a href="https://github.com/nhs-oa-community" aria-label="Go to NHS-OA's GitHub" title="github" target="_blank" rel="noopener">
        <i class="link-dark me-1" aria-hidden="true"></i> {{< fa brands github >}}</a>
      <a href="https://www.linkedin.com/in/nhs-oa-community-2555a6282/" aria-label="Go to NHS-OA's LinkedIn" title="LinkedIn" target="_blank" rel="noopener">
        <i class="link-dark me-1" aria-hidden="true"></i> {{< fa brands linkedin >}}</a>

    right:
      - text: "Terms and Conditions"
        href: ts-and-cs.qmd
        aria-label: Terms and Conditions
      - text: "Contact"
        href: contact.qmd
        aria-label: Contacts on About Page
      - text: "Licence"
        href: LICENSE.md
        aria-label: Licence Details

format:
  html:
    css: styles/styles.css

execute:
  freeze: auto
  warning: false

