---
title: "About NHS Open Analytics Community"
format: html
---

The NHS Open Analytics Community was formed in 2025 by an enthusiastic group of 
volunteers from across the NHS. The much loved NHS-R and NHS.pycom communities
were merged to allow a stronger voice in support of NHS analysts and data
scientists who care about promoting the use of open code and tools in health and 
care.

We aim to promote best practice and values of transparency, sharing, and
collaboration in the use of health and care data, but we also welcome those who
share our values from the public sector, academia, and the third sector. 

We are coding language-agnostic, but principally provide resources and training
in R and python.

NHS-OA is hosted by [The Strategy Unit](https://www.strategyunitwm.nhs.uk/).

## How can I get involved?

Whether you are a complete novice at coding or a seasoned professional, a 
senior leader or on day one of your career, the community has something to 
offer you!

📢 Join the conversation over on [Slack](https://nhsoacommunity.slack.com)!

📖 Check out our free online [books](books/index.qmd) and [training materials](training/index.qmd)!

🎪 Come along to one of our [events](events/events.qmd)!

📽️ [Watch](https://www.youtube.com/@NHSOA_Community) our previous conferences, webinars and workshops on all manner of topics!

🪄 [Contribute](https://github.com/nhs-oa-community) to our codebases - including this website!

😎 Join the [committee](mailto: openanalytics.community@nhs.net) and have your say on how we run!

## Statement on open code

NHS Open Analytics (NHS OA) is a community of analysts, data scientists, clinicians, and others from across health and social care. As individuals, our members make use of numerous tools and approaches to harness the power and potential of data to support the health of the nation and the work of the NHS.

The NHS OA community strives to ensure that materials, software, and analytical methods are made freely available to system partners and the wider public in the interests of collaboration, improvement and reproducibility. This is aligned with the open source movement.

**Why is this important?**

NHS colleagues use software and code to understand and improve healthcare provision across the nation.

Open analytical code promotes transparency, trust, and learning across the NHS. By making methods and code openly available, analytical work can be reviewed, challenged, improved, and reproduced by others. This helps to identify errors, share best practice, and build confidence in the statistics and insights used to inform decision-making. As the NHS continues to make greater use of data, advanced analytics, and artificial intelligence, openness in the methods used to generate evidence will be essential to maintaining public trust and ensuring that innovation is delivered safely and consistently.

At NHS OA, we recognise the importance of sharing code, establishing standards for analysis, and using consistent methods nationally. We advocate for the open publication of analytical code and encourage the reuse of code.

The adoption and reuse of open analytical code represent a significant opportunity for the NHS to improve reporting standards, reduce variation in the statistics generated by providers, and free up time for analysts, data scientists, and clinicians to focus on new ways of using data to support the NHS in delivering better care for the nation.

