---
date: "2025-02-12T10:00:00+00:00"
title: "Accessibility commitment"
---

Return to [home page](/) or [about page](/about).

The NHS-OA Community welcomes feedback on the accessibility of this site and any links to its materials, including code and training materials.

We have used the [Web Accessibility Evaluation Tool](https://wave.webaim.org/) to manually check for accessibility errors and corrected where possible.

# Reporting accessibility problems with this website

We are always looking to improve the accessibility of this website. Please let us know if you find any problems not listed on this page or if we are not meeting accessibility requirements, email [openanalytics.community@nhs.net](mailto:openanalytics.community@nhs.net).

## Website practices

This site has been designed with the following features in mind:

- A sans serif font is used.
- Alternative text is used for all images.

# Non-accessible content

## Default thumbnail image for blogs - no alternative text

Thumbnails for default images in blogs do not have alternative text.
In code this relates to the `image-placeholder:`.

There is an open [issue](https://github.com/quarto-dev/quarto-cli/issues/7028) on Quarto's GitHub.

## Empty and redundant links

In the blog page, images have missing links and redundant links.

## YouTube video links

There are links to YouTube videos in this website that currently only have the automated YouTube subtitles.

# Contrast Errors

Tags in the book and blog page do not meet the minimum contrast threshold.
