---
title: "NHS-OA Training"
---

The NHS-OA Community provides online small group training in coding on a 
semi-regular basis.  
This training is delivered by volunteers and is typically held over two half-day
sessions.
Training is free of charge to those eligible to attend, which includes the groups listed below. 
Eligibility is assessed based on the applicant submitting their application using
an email address with a relevant domain (e.g. name@nhs.net).
Private email addresses will not be accepted unless the applicant can prove
retirement from one of the occupations covered by the list below.

- NHS employees
- Academics
- Government employees
- Civil Servants
- Voluntary Sector/Charities

## Current Training Courses (all held on MS Teams)

### SEPTEMBER 2026

📆 15th & 16th **Introduction to R and R Studio with Zoë Turner**:

_From ‘Hello World’ to producing a basic report._

_This introduction takes you from no knowledge of R to teaching you the basics of 
the R studio environment, then loading in some data, some common data wrangling 
tasks, some charting and finishing with pulling it all together to produce a 
simple automated report._  

_No previous knowledge is required. This workshop will utilise the cloud, with all 
datasets provided as part of the course material, so no specialist set up is 
required._

+ Workshop
+ 09:00 - 13:00 (BST)
+ 🔗 [Register to attend here](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UM0pRTVZLVVJDSzVVWjFXRTI1VTFXVFVVSS4u)

### OCTOBER 2026

📆 13th & 14th **Intermediate R with Zoë Turner**:

_This course is designed to follow on from the Introduction to R and R Studio 
course, noting that attendees should be familiar with the basics covered in the 
workshop._

_Please be advised that this session will go into more depth and complex wrangling 
tasks, explore how to use the NHS-R SPC plot the dots library and cover in very 
simple terms an understanding of some functional programming. 
This workshop will utilise the cloud, with all datasets provided as part of the 
course material, so no specialist set up is required._

+ Workshop
+ 09:00 - 13:00 (BST)
+ 🔗 [Register to attend here](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UMzU2SDYwWEgxS0lIQjhSNjJKQk40R08zMi4u)

## Training materials

All training materials are publicly available.
This includes materials used for teaching courses that are no longer regularly
held.
Please see our [GitHub page](https://github.com/nhs-oa-community) for further details.


## Can I volunteer to host or co-host future training?

Absolutely! 

We'd love for more volunteers to step forwards to provide this teaching.
All materials are provided and support is available.
If you'd like to take part, drop us an email at [openanalytics.community\@nhs.net](mailto:openanalytics.community@nhs.net).