---
title: "Upcoming Community Events"
---

We hold regular events throughout the year. 
These range in their level of interactivity; 

- **webinars** that are structured like short lectures on varied topics with time 
for questions at the end (often).
- **workshops** of varying lengths for smaller groups to be shown a particular set
of skills from an experienced presenter.
- [**Coffee and Coding**](#sec-coffee) an informal friendly community session to share 
tips, chat and hear advances in the state of the art(s).

## 🧑‍🏫 Workshops and webinars

Please note:

- Workshop attendance is restricted to UK employees of the NHS, public sector, 
civil service, voluntary sector, charities and academia, or who are retirees 
from any of these sectors. 
Please note you must sign up with a work email address to verify your credentials.
- Webinars are free to all to attend, and recordings are stored on our [YouTube Channel](https://www.youtube.com/@NHSOA_Community).

-----

### SEPTEMBER 2026


📆 10th **UK Address Matcher: High performance free address matching software with 
Tom Hepworth**:

_Address matching is a common challenge when working with messy, inconsistent, 
or incomplete address data. 
In this webinar, we’ll introduce uk_address_matcher, an open-source Python 
package for matching UK addresses to canonical address datasets such as Ordnance 
Survey AddressBase or OS NGD. 
We’ll demonstrate how the package can be used to run fast, transparent, and 
reproducible address matching workflows, including how to interpret match scores 
and choose appropriate thresholds. 
The session will also introduce ukam_os_builder, a companion package that helps 
users quickly access and prepare Ordnance Survey data under PSGA licensing, 
making it easier to get started with high-quality reference data. 
The webinar will include practical examples and discussion of how these tools 
can support robust analytical pipelines._

Links: 

[uk_address_matcher](https://github.com/moj-analytical-services/uk_address_matcher)
[ukam_os_builder](https://github.com/moj-analytical-services/ukam_os_builder)

+ Webinar
+ 10:30 - 11:30 (BST)
+ 🔗 [Register to attend here](https://events.teams.microsoft.com/event/f4913672-0d1a-4509-b1b5-35ec2d96dc30@37c354b2-85b0-47f5-b222-07b48d774ee3)

📆 15th & 16th **Introduction to R and R Studio with Zoë Turner**:

_From ‘Hello World’ to producing a basic report._

_This introduction takes you from no knowledge of R to teaching you the basics of 
the R studio environment, then loading in some data, some common data wrangling 
tasks, some charting and finishing with pulling it all together to produce a 
simple automated report._  

_No previous knowledge is required. This workshop will utilise the cloud, with all 
datasets provided as part of the course material, so no specialist set up is 
required._

+ Workshop
+ 09:00 - 13:00 (BST)
+ 🔗 [Register to attend here](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UM0pRTVZLVVJDSzVVWjFXRTI1VTFXVFVVSS4u)

## OCTOBER 2026

📆 13th & 14th **Intermediate R with Zoë Turner**:

_This course is designed to follow on from the Introduction to R and R Studio 
course, noting that attendees should be familiar with the basics covered in the 
workshop._

_Please be advised that this session will go into more depth and complex wrangling 
tasks, explore how to use the NHS-R SPC plot the dots library and cover in very 
simple terms an understanding of some functional programming. 
This workshop will utilise the cloud, with all datasets provided as part of the 
course material, so no specialist set up is required._

+ Workshop
+ 09:00 - 13:00 (BST)
+ 🔗 [Register to attend here](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UMzU2SDYwWEgxS0lIQjhSNjJKQk40R08zMi4u)


## ☕ Coffee and Coding 🍵 {#sec-coffee} 

To register your interest in attending future Coffee & Coding session, please
complete [this short form](https://forms.office.com/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UQTVJUjlZVVFUN1RNMjlMM0NUQkk5NTczMS4u).

:::{.callout-important}
NB. Completing this form will allow you to be sent invitations to all future
Coffee & Coding events (both the Wednesday and Thursday sessions).
:::

📆 WEDNESDAYS **Coffee and Coding**:

+ Host: Simon Wellesley-Miller (NHSE)
+ 11:30 - 12:30 (GMT)

📆 THURSDAYS **Coffee and Coding**:

+ Host: Lucy Spencer (DHSC)
+ 10:30 - 11:30 (GMT)

## What is Coffee & Coding?

Coffee and Coding is a core initiative of the NHS-OA Community, designed to 
provide an informal, supportive space for NHS, DHSC and the wider health and 
social care sector to share knowledge about Open Source open-source analytics 
(mainly R & Python).

It’s essentially a "community of practice" where the focus is on learning from 
peers rather than formal classroom instruction.

## What Happens in a Session?

The sessions typically last an hour and are held virtually (via MS Teams). 
While they are organic and informal, they generally follow a loose structure:

- **Show and Tell**: One or more members demonstrate a piece of code they’ve 
written, a new package they’ve discovered, or a dashboard they’ve built.

- **Library/Tip of the Week**: A quick highlight of a useful tool or shortcut 
that makes analytical life easier.

- **Code Surgery**: A space for members to bring "code dilemmas." 
You can share your screen and get live help from the community on a specific bug, 
logic problem or just general advice.

- **General Discussion**: Open floor for networking and discussing broader topics 
like RAP (Reproducible Analytical Pipelines), visualisation techniques, data 
science etc.

## Key Rules and Ethos

The community operates on a few specific principles to keep the environment safe 
and productive:

- Recording: We record and publish our Coffee and Coding sessions. 
By joining the session, you consent to your voice, image and any questions you 
submit being recorded and subsequently published. 

- "Vegas rules": If we decide not to record a session, "vegas rules" are applied 
to ensure people feel comfortable asking "simple" questions or admitting they 
are stuck. 
(Vegas Rules – what happens in Vegas – stays in Vegas)

- No Patient Data: This is strictly enforced. 
Code is shared using "dummy" or synthetic data; real patient data is never shown.

- Inclusivity: It is aimed at all skill levels. 
A typical session is roughly 40% beginners, 45% intermediate, and 15% advanced 
users.

- First Rule of C&C: "Tell everyone about Coffee and Code"—the goal is to grow 
the open-source movement within the healthcare sector.

:::{.callout-important}
If you would like to request the removal of a recording, please contact the [NHS Open Analytics Community mailbox](mailto:openanalytics.community@nhs.net).
:::

## How to Join

- Frequency: Sessions usually happen every weeks, rotating between different days 
(Wednesdays & Thursdays) to ensure people with different shift patterns or 
part-time schedules can attend.

- Booking: See above links.

- Slack: Much of the follow-up and resource sharing happens on the [NHS-OA Community Slack channel](https://nhsoacommunity.slack.com/), which is a great place to stay connected between sessions.

## Why go?

If you are an analyst in the NHS, it’s one of the best ways to break out of your 
silo. 
You’ll find that someone else has almost always faced the same problem you’re 
currently struggling with, and they’ve likely already written a script to solve 
it.

Its always great to see what other people are up to and be inspired and share 
ideas, you just don’t know what you don’t know – this is a safe space to find 
out.

We want to share the cool stuff we are doing and help the community to thrive to 
support patient care.

Previous recorded sessions (from before the merger with DHSC Coffee & Code) can 
be found [here](https://future.nhs.uk/NHSERcommunity/view?objectID=41908688).
