---
title: "RAP Drop Ins"
---

Reproducible Analytical Pipelines are the bedrock of modern analytical efficiency,
and a key element in NHS-OA's vision.
These drop in sessions, run by the RAP sub-committee of NHS-OA and the Strategy Unit,
are designed to offer a space to ask the 'stupid questions' 
(Hint: _there aren't any!_), discuss how to up your RAP game and get great tips from
your colleagues across the NHS.

Whether you're RAP‑curious or already deep into reproducible workflows, this 
session gives you a friendly, hands‑on space to learn with NHS colleagues. 
Expect real challenges, real solutions, and practical tips you can use the same day!


## What is RAP? 

RAP (Reproducible Analytical Pipelines) is a set of principles and working practices that help you create faster, more robust, and more transparent analytical processes.
 
## Why is RAP important?

RAP helps us to:

- Improve the transparency and ethics by showing our workings and giving users a way to feed back into our processes.
- Improve the accessibility of data by outputting data in a consistent, predictable, and accessible format for users.
- Improve the quality of data by ensuring good coding standards are applied.
- Improve the utility of data by sharing code. This shows users how the data have been produced and allowing them to reuse our code.
- Improve the reliability of data by automating manual steps where possible.

## What happens in a RAP drop-in session? 

Come along and ask us anything about Python, R, SQL, Git, GitHub, or even how to do RAP in general! 
It is an open-door session, come and go as you please! Sessions are typically made up of a mix of RAP Veterans and those just starting their RAP journey.
Anyone can ask a question, and everyone can answer. The facilitators will ensure everyone has a chance to do both, as well as capturing questions and answers to be recorded on the [RAP Drop-In Discussions Page](https://github.com/nhs-oa-community/RAP_Drop_In/discussions).
This is not just a place for computer whizzes; managers are welcome to come and ask questions! There are no stupid questions or questions that are asked too much!
RAP drop-in sessions take place every other Wednesday, from 10:00 until 11:00 UK time, via MS Teams.

## Key Rules and Ethos

The community operates on a few specific principles to keep the environment safe and productive:

- No attribution: No question is too simple. Ask it or say when you are stuck. We summarise questions and answers as GitHub Discussions so others can learn from them, but we avoid saying who said what, or which team or organisation they are from.
- No Patient Data: This is strictly enforced. Code is shared using “dummy” or synthetic data; real patient data is never shown.
- Inclusivity: It is aimed at all skill levels.
- Tell everyone about RAP – the goal is to grow the open-source movement within the healthcare sector.
- Disrespectful, disruptive and/or abusive behaviour will NOT be tolerated. It is at the discretion of the host to remove any attendees that exhibit this behaviour. 
For additional information, please refer to the [NHS Open Analytics Community Code of Conduct](https://nhsoa.uk/CODE_OF_CONDUCT.html).

## Who can attend?

Attendance is restricted to UK employees of the NHS, public sector, civil service, voluntary sector, charities and academia, or who are retirees from any of these sectors. Please note you must sign-up with a work email address to verify your credentials.

## Why attend?

RAP drop-in sessions are a great opportunity to network and collaborate with a diverse community of analysts, ranging from beginner to advanced, experienced in the use of Python, R, SQL, Git and GitHub, automation, reproducibility, smarter workflows and more.

## How to register

Please complete this [short form](https://www.smartsurvey.co.uk/s/XPUHSJ) to register your interest to attend the RAP drop-in sessions. You will then receive a reoccurring MS Teams meeting invite from the NHS Open Analytics Community Team.
NB. By completing the registration form, you will be permitting the NHS Open Analytics Community Team to contact you directly regarding invitations to RAP drop-in sessions and related events.

## IG Statement

Any data/information collected (from you) will be used for the purpose of administration within the NHS Open Analytics Community. Please be advised that the aforementioned data may be accessed by employees of the Department for Health and Social Care, NHS England, The Strategy Unit and/or agreed event partners, of whom are members of the NHS Open Analytics Community Team, NHS Open Analytics Community Committee and/or are event hosts. Any data/information collected (from you) will not be disclosed to any third party, except within the terms of the UK Data Protection Act 2018. 
In addition, the data/information recorded in the registration form listed above will be used to support the NHS-Open Analytics Community, Department for Health and Social Care, NHS England, The Strategy Unit and/or agreed event partner's event management, marketing and market research activities. 
It is important to note that you have the right to withdraw consent for the collection of your data at any point and can do so by contacting the [NHS Open Analytics Community Team](openanalytics.community@nhs.net). 

