---
title: "🧑‍🏫 Workshops and webinars"
---


:::{.callout-note}
Please note:

- Workshop attendance is restricted to UK employees of the NHS, public sector, 
civil service, voluntary sector, charities and academia, or who are retirees 
from any of these sectors. 
Please note you must sign up with a work email address to verify your credentials.
- Webinars are free to all to attend, and recordings are stored on our [YouTube Channel](https://www.youtube.com/@NHSOA_Community).

## IG Statement

Any data/information collected (from you) will be used for the purpose of administration within the NHS Open Analytics Community. Please be advised that the aforementioned data may be accessed by employees of The Strategy Unit and/or agreed event partners, of whom are members of the NHS Open Analytics Community Team, NHS Open Analytics Community Committee and/or are event hosts. Any data/information collected (from you) will not be disclosed to any third party, except within the terms of the UK Data Protection Act 2018. 
In addition, the data/information recorded in the registration form will be used to support the NHS-Open Analytics Community, The Strategy Unit and agreed event partner's event management, marketing and market research activities. 
It is important to note that you have the right to withdraw consent for the collection of your data at any point and can do so by contacting the [NHS Open Analytics Community Team](openanalytics.community@nhs.net). 


:::
